WT-15513 Turn on ASAN for python testing in evergreen

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -871,10 +871,22 @@ functions:
           echo "Using num_jobs '-j ${num_jobs}' for 'unit test'"
           threads_command="-j ${num_jobs}"
         fi
+        # Set LD_PRELOAD to enable ASAN testing of python tests. Check that LD_PRELOAD isn't already
+        # set as that would be incompatible.
+        if [[ ! -z "${asan_preload}" ]]; then
+            if [[ ! -z "${LD_PRELOAD}"]]; then
+                echo "ERROR: LD_PRELOAD is already set, this is incompatible with python asan testing"
+                exit 1
+            fi
+            export LD_PRELOAD=`/opt/mongodbtoolchain/v5/bin/clang -print-file-name=libclang_rt.asan.so`
+        fi
         if [ ${check_coverage|false} = true ]; then
             ${python_binary|python3} ../test/suite/run.py ${ignore_stdout} ${unit_test_args|-v 2} ${unit_test_variant_args} $threads_command $(cat $do_run) 2>&1 || echo "Ignoring failed test as we are checking test coverage"
         else
             ${python_binary|python3} ../test/suite/run.py ${ignore_stdout} ${unit_test_args|-v 2} ${unit_test_variant_args} $threads_command $(cat $do_run) 2>&1
+        fi
+        if [[ ! -z "${asan_preload}" ]]; then
+            export LD_PRELOAD=
         fi
 
   "unit test tsan parallel":
@@ -6479,13 +6491,21 @@ buildvariants:
     CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/clang.cmake
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=ASan
     ENABLE_TCMALLOC: 0
+    # PYTHONMALLOC is key to avoiding a long suppression list when running python under ASan. It
+    # turns off python's own allocators and uses the default system allocators.
+    # Then ASan symbolizer is intentionally set to toolchain v4 because the v5 symbolizer leaks
+    # memory which triggers recursion.
     additional_env_vars: |
       export LSAN_OPTIONS="$COMMON_SAN_OPTIONS:print_suppressions=0:suppressions=$(git rev-parse --show-toplevel)/test/evergreen/asan_leaks.supp"
+      export ASAN_SYMBOLIZER_PATH=/opt/mongodbtoolchain/v4/bin/llvm-symbolizer
+      export PYTHONMALLOC=malloc
     num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    asan_preload: true
     # Exclude wt12015_backup_corruption for ASan builds. It creates false positives when it deliberately kills processes that invoke corruption.
     ctest_extra_args: -E "wt12015_backup_corruption"
   tasks:
     - name: ".pull_request !.pull_request_compilers !.python !.tiered_unittest !csuite-wt12015-backup-corruption-test"
+    - name: ".unit_test"
     - name: examples-c-test
     - name: format-asan-smoke-test
     - name: model-test-long
