WT-5372 Updated format-stress-sanitizer-test to skip known errors

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -1934,23 +1934,33 @@ tasks:
     commands:
       - func: "get project"
       - func: "compile wiredtiger address sanitizer"
-      - func: "format test script"
-        vars:
-          test_env_vars: ASAN_OPTIONS="detect_leaks=1:abort_on_error=1:disable_coredump=0" ASAN_SYMBOLIZER_PATH=/opt/mongodbtoolchain/v3/bin/llvm-symbolizer
-          # run for 24 hours ( 24 * 60 = 1440 minutes), don't stop at failed tests, use default config
-          format_test_script_args: -t 240
       - command: shell.exec
         params:
           working_dir: "wiredtiger/test/format"
           shell: bash
           script: |
-            set -o errexit
             set -o verbose
 
-            if [ $(grep -c "heap-use-after-free" RUNDIR.*) -ne 0 ] && [ $(grep -c "__wt_btcur_next_random" RUNDIR.*) -ne 0 ]
+            ASAN_OPTIONS="detect_leaks=1:abort_on_error=1:disable_coredump=0" ASAN_SYMBOLIZER_PATH=/opt/mongodbtoolchain/v3/bin/llvm-symbolizer
+
+            # run for 24 hours ( 24 * 60 = 1440 minutes), don't stop at failed tests, use default config
+            ${test_env_vars|} ${format_test_setting|} ./format.sh ${smp_command|} -t 200 2>&1
+
+            # If any of the format job fails i.e, format.sh script returns 1 then we need to check if
+            # it failed with any of the known errors.
+
+            # Known errors to be skipped are
+            # *  heap-use-after-free && __wt_btcur_next_random
+            
+            if [ $? -ne 0 ]
             then
-              echo "Found heap-use-after-free & __wt_btcur_next_random error"
-              exit 0
+              echo "There are some failed jobs."
+              ret=`grep -q --exclude-dir=RUNDIR.* "heap-use-after-free" RUNDIR.*.log && grep --exclude-dir=RUNDIR.* "__wt_btcur_next_random" RUNDIR.* | wc -l`
+              if [ "$ret" != 0 ]
+              then
+                echo "Found heap-use-after-free & __wt_btcur_next_random error"
+                exit 0
+              fi
             fi
   
   - name: format-stress-sanitizer-smoke-test
