Fix TCMalloc and num threads

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -50,7 +50,7 @@ functions:
               export LD_LIBRARY_PATH=$WT_BUILDDIR
             fi
 
-            if [[ "${enable_tcmalloc}" =~ true ]]; then
+            if ! [[ "${ENABLE_TCMALLOC}" =~ "ENABLE_TCMALLOC=0" ]]; then
               export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$WT_TOPDIR/TCMALLOC_LIB/lib"
               export LD_PRELOAD=$WT_TOPDIR/TCMALLOC_LIB/lib/libtcmalloc.so
             fi
@@ -68,6 +68,12 @@ functions:
               export UBSAN_OPTIONS="$COMMON_SAN_OPTIONS:print_stacktrace=1"
             fi
 
+            if [ -n "${num_threads}" ]; then
+              num_threads="${num_threads}"
+            else
+              num_threads="-j $(grep -c ^processor /proc/cpuinfo)"
+            fi
+            echo $num_threads
             ${additional_env_vars}
         # The expansion is used for any task that requires the mongodbtoolchain binaries.
         - key: PREPARE_PATH
@@ -77,9 +83,14 @@ functions:
             else
               export PATH=/opt/mongodbtoolchain/v4/bin:$PATH
             fi
-        # The expansion is used for any task that requires the mongodbtoolchain binaries.
-        - key: smp_command
-          value: -j $(grep -c ^processor /proc/cpuinfo)
+
+            if [ -n "${num_threads}" ]; then
+              num_threads="${num_threads}"
+            else
+              num_threads="-j $(grep -c ^processor /proc/cpuinfo)"
+            fi
+            echo $num_threads
+
 
   "get project":
     command: git.get_project
@@ -163,6 +174,7 @@ functions:
           ${CMAKE_INSTALL_PREFIX|-DCMAKE_INSTALL_PREFIX=$(pwd)/cmake_build/LOCAL_INSTALL} \
           ${CMAKE_PREFIX_PATH|-DCMAKE_PREFIX_PATH="$(pwd)/TCMALLOC_LIB"} \
           ${CMAKE_TOOLCHAIN_FILE|-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/mongodbtoolchain_stable_gcc.cmake} \
+          ${ENABLE_TCMALLOC|-DENABLE_TCMALLOC=1}
           ${NONSTANDALONE|} \
           ${ENABLE_SHARED|} \
           ${ENABLE_STATIC|} \
@@ -227,7 +239,7 @@ functions:
         else
           echo "Using config flags $DEFINED_EVERGREEN_CONFIG_FLAGS ${posix_configure_flags|}"
           # Fetch the gperftools library if needed. This will also get tcmalloc.
-          if [[ "$DEFINED_EVERGREEN_CONFIG_FLAGS ${posix_configure_flags|}" =~ (tcmalloc|TCMALLOC) ]] && ! [[ "$DEFINED_EVERGREEN_CONFIG_FLAGS ${posix_configure_flags|}" =~ "ENABLE_TCMALLOC=0" ]] && [ ! -d "./automation-scripts" ]; then
+          if  [[ "$DEFINED_EVERGREEN_CONFIG_FLAGS ${posix_configure_flags|}" =~ "ENABLE_TCMALLOC=1" ]] && [ ! -d "./automation-scripts" ]; then
             is_cmake_build=true
             git clone git@github.com:wiredtiger/automation-scripts.git
             . automation-scripts/evergreen/find_gperftools.sh ${s3_access_key} ${s3_secret_key} ${build_variant} $is_cmake_build
@@ -274,9 +286,9 @@ functions:
           # Compiling with CMake generated Ninja file.
           cd cmake_build
           if [ "${cmake_generator|Ninja}" = "Ninja" ]; then
-            ninja ${smp_command|} 2>&1
+            ninja ${num_threads} 2>&1
           else
-            make ${smp_command|} 2>&1
+            make ${num_threads} 2>&1
           fi
         fi
         echo "Ending 'make wiredtiger' step"
@@ -397,7 +409,7 @@ functions:
               pushd cmake_build
               # Adding -DENABLE_PYTHON=1 -DENABLE_STRICT=1 as 6.0 does not default these like develop.
               $CMAKE -DCMAKE_C_FLAGS="-DMIGHT_NOT_RUN -Wno-error" -DENABLE_PYTHON=1 -DENABLE_STRICT=1 ../.
-              make -C lang/python ${smp_command|}
+              make -C lang/python ${num_threads}
             fi
             # Pop to root project directory.
             popd
@@ -475,7 +487,7 @@ functions:
         ${PREPARE_TEST_ENV}
         . test/evergreen/find_cmake.sh
         cd cmake_build/${directory}
-        $CTEST ${smp_command|} --output-on-failure 2>&1
+        $CTEST ${extra_args} --output-on-failure 2>&1
   "make check all":
     command: shell.exec
     params:
@@ -487,8 +499,8 @@ functions:
         ${PREPARE_TEST_ENV}
         . test/evergreen/find_cmake.sh
         cd cmake_build
-        echo "Using smp_command '${smp_command}' for 'make check all'"
-        $CTEST -L check ${smp_command|} --output-on-failure ${check_args|} 2>&1
+        echo "Using num threads '${num_threads}' for 'make check all'"
+        $CTEST -L check ${num_threads} --output-on-failure ${check_args|} 2>&1
 
   "cppsuite test":
     - command: shell.exec
@@ -591,11 +603,11 @@ functions:
         set -o verbose
         ${PREPARE_TEST_ENV}
         cd cmake_build
-        echo "Using smp_command '${smp_command}' for 'unit test'"
+        echo "Using num_threads '${num_threads}' for 'unit test'"
         if [ ${check_coverage|false} = true ]; then
-            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} ${smp_command|} 2>&1 || echo "Ignoring failed test as we are checking test coverage"
+            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} ${num_threads} 2>&1 || echo "Ignoring failed test as we are checking test coverage"
         else
-            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} ${smp_command|} 2>&1
+            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} ${num_threads} 2>&1
         fi
 
   "code coverage analysis":
@@ -729,7 +741,7 @@ functions:
         ${PREPARE_TEST_ENV}
         ${format_test_setting|}
         for i in $(seq ${times|1}); do
-          ./format.sh ${smp_command|} ${format_test_script_args|} 2>&1
+          ./format.sh ${num_threads} ${format_test_script_args|} 2>&1
         done
   "format test tiered":
     command: shell.exec
@@ -1253,13 +1265,13 @@ variables:
       # We'll explicitly use the python3 in /usr/bin, we use the same in configuring cmake.
       CMAKE_TOOLCHAIN_FILE:
       CC_OPTIMIZE_LEVEL: -DCC_OPTIMIZE_LEVEL=-O0
-      smp_command: -j $(echo $(sysctl -n hw.logicalcpu) / 2 | bc)
+      num_threads: -j $(echo $(sysctl -n hw.logicalcpu) / 2 | bc)
       cmake_generator: "Unix Makefiles"
       additional_env_vars: |
         export LD_LIBRARY_PATH=""
         export DYLD_LIBRARY_PATH=$WT_BUILDDIR
       # Must disable TCMALLOC as it may be picked up locally and its not on all hosts.
-      posix_configure_flags: -DENABLE_TCMALLOC=0
+      ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     tasks:
       - name: compile
       - name: make-check-test
@@ -1413,20 +1425,25 @@ tasks:
       - command: expansions.update
         params:
           updates:
-            - key: CMAKE_TOOLCHAIN_FILE
-              value: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/gcc.cmake
+          - key: CMAKE_TOOLCHAIN_FILE
+            value: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/gcc.cmake
       - func: "get project"
       - func: "compile wiredtiger"
+        vars:
           CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=Release
       - func: "compile wiredtiger"
+        vars:
           HAVE_DIAGNOSTIC: -DHAVE_DIAGNOSTIC=0
           CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=Debug
       - func: "compile wiredtiger"
+        vars:
           GNU_C_VERSION: -DGNU_C_VERSION=7
       - func: "compile wiredtiger"
+        vars:
           GNU_C_VERSION: -DGNU_C_VERSION=8
           GNU_CXX_VERSION: -DGNU_CXX_VERSION=8
       - func: "compile wiredtiger"
+        vars:
           GNU_C_VERSION: -DGNU_C_VERSION=9
           GNU_CXX_VERSION: -DGNU_CXX_VERSION=9
 
@@ -1436,8 +1453,8 @@ tasks:
       - command: expansions.update
         params:
           updates:
-            - key: CMAKE_TOOLCHAIN_FILE
-              value: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/clang.cmake
+          - key: CMAKE_TOOLCHAIN_FILE
+            value: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/clang.cmake
       - func: "get project"
       - func: "compile wiredtiger"
         vars:
@@ -2643,7 +2660,7 @@ tasks:
             set -o errexit
             set -o verbose
             ${PREPARE_TEST_ENV}
-            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} --hook tiered=tier_storage_source='s3_store' ${smp_command|} 2>&1
+            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} --hook tiered=tier_storage_source='s3_store' ${num_threads} 2>&1
 
   - name: unit-test-hook-tiered-timestamp
     tags: ["python"]
@@ -2711,7 +2728,7 @@ tasks:
       - func: "compile wiredtiger"
       - func: "make check directory"
         vars:
-          smp_command: -L long_running
+          extra_args: -L long_running
 
   # Break out Python unit tests into multiple buckets/tasks.  We have a fixed number of buckets,
   # and we use the -b option of the test/suite/run.py script to split up the tests.
@@ -4349,7 +4366,7 @@ tasks:
             set -o errexit
             set -o verbose
             ${PREPARE_TEST_ENV}
-            ./run_format_configs.sh ${smp_command|}
+            ./run_format_configs.sh ${num_threads}
 
   - name: static-wt-build-test
     commands:
@@ -6072,8 +6089,7 @@ buildvariants:
   run_on:
   - ubuntu2004-test
   expansions:
-    enable_tcmalloc: true
-    smp_command: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_threads: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
     data_validation_stress_test_args: -t r -m -W 3 -D -p -n 100000 -k 100000 -C cache_size=100MB
   tasks:
     - name: ".pull_request !.pull_request_compilers"
@@ -6128,7 +6144,6 @@ buildvariants:
   expansions:
     CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/clang.cmake
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=ASan
-    enable_tcmalloc: true
     additional_env_vars: |
       export LSAN_OPTIONS="$COMMON_SAN_OPTIONS:print_suppressions=0:suppressions=$(git rev-parse --show-toplevel)/test/evergreen/asan_leaks.supp"
       export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libeatmydata.so:$LD_PRELOAD"
@@ -6144,8 +6159,9 @@ buildvariants:
   run_on:
   - ubuntu2004-test
   expansions:
+    ENABLE_CPPSUITE: -DENABLE_CPPSUITE=0 
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     posix_configure_flags: -DENABLE_PYTHON=0 -DENABLE_LZ4=0 -DENABLE_SNAPPY=0 -DENABLE_ZLIB=0 -DENABLE_ZSTD=0
-    ENABLE_CPPSUITE: -DENABLE_CPPSUITE=0
   tasks:
     - name: compile
     - name: make-check-test
@@ -6193,9 +6209,7 @@ buildvariants:
     # Use optimisation level -O0 since Clang treats -Og (our default optimisation for non-release 
     # builds) as -O1, making test binaries more difficult to debug. 
     CC_OPTIMIZE_LEVEL: -DCC_OPTIMIZE_LEVEL=-O0
-    enable_tcmalloc: true
-    additional_env_vars: |
-      export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libeatmydata.so
+    additional_env_vars: export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libeatmydata.so
   tasks:
     - name: clang-analyzer
     - name: compile
@@ -6214,8 +6228,6 @@ buildvariants:
   display_name: "! Ubuntu 20.04 Compilers"
   run_on:
   - ubuntu2004-wt-build
-  expansions:
-    enable_tcmalloc: true
   tasks:
     - name: ".pull_request_compilers"
 
@@ -6225,7 +6237,6 @@ buildvariants:
   - ubuntu2004-small
   expansions:
     additional_env_vars: export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libeatmydata.so:$LD_PRELOAD"
-    enable_tcmalloc: true
   tasks:
     # FIXME-WT-11606 Remove this temporary task.
     - name: format-11507-test
@@ -6259,7 +6270,6 @@ buildvariants:
   - ubuntu2004-arm64-large
   expansions:
     additional_env_vars: export LD_PRELOAD="/usr/lib/aarch64-linux-gnu/libeatmydata.so:$LD_PRELOAD"
-    enable_tcmalloc: true
   tasks:
     # FIXME-WT-11606 Remove this temporary task.
     - name: format-11507-test
@@ -6282,8 +6292,6 @@ buildvariants:
   run_on:
   # We run on medium as small has too small a disk.
   - ubuntu2004-medium
-  expansions:
-    enable_tcmalloc: true
   tasks:
     - name: compile
     - name: compile-nonstandalone
@@ -6295,8 +6303,6 @@ buildvariants:
   batchtime: 720 # twice a day
   run_on:
   - ubuntu2004-arm64-large
-  expansions:
-    enable_tcmalloc: true
   tasks:
     - name: compile
     - name: compile-nonstandalone
@@ -6317,6 +6323,7 @@ buildvariants:
   run_on:
   - ubuntu2004-test
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     additional_env_vars: export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libeatmydata.so:$LD_PRELOAD"
   tasks:
     - name: compile-linux-no-ftruncate
@@ -6329,6 +6336,7 @@ buildvariants:
   run_on:
   - rhel80-test
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     additional_env_vars: export LD_PRELOAD="/usr/local/lib/libeatmydata.so:$LD_PRELOAD"
     cmake_generator: "Unix Makefiles"
     CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/gcc.cmake
@@ -6355,6 +6363,7 @@ buildvariants:
   run_on:
   - windows-64-vs2017-test
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     # Remove the default configurations for the toolchain and install prefix.
     CMAKE_TOOLCHAIN_FILE:
     CMAKE_INSTALL_PREFIX:
@@ -6394,6 +6403,7 @@ buildvariants:
   - ubuntu1804-large
   batchtime: 4320 # 3 days
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     # Must disable ZSTD as its not available on the big endian platform (we generate the data files used for those tests here).
     posix_configure_flags: -DENABLE_ZSTD=0
   tasks:
@@ -6408,6 +6418,7 @@ buildvariants:
   - rhel80-zseries-build
   batchtime: 4320 # 3 days
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     posix_configure_flags: -DENABLE_ZSTD=0
   tasks:
     - name: compile
@@ -6423,9 +6434,10 @@ buildvariants:
   expansions:
     format_test_setting: ulimit -c unlimited
     CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/mongodbtoolchain_stable_clang.cmake
-    ENABLE_CPPSUITE: -DENABLE_CPPSUITE=0
     # Use quarter of the vCPUs to avoid OOM kill failure and disk issues on this variant.
-    smp_command: -j $(echo $(grep -c ^processor /proc/cpuinfo) / 4 | bc)
+    num_threads: -j $(echo $(grep -c ^processor /proc/cpuinfo) / 4 | bc)
+    ENABLE_CPPSUITE: -DENABLE_CPPSUITE=0
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     posix_configure_flags: -DENABLE_STRICT=0
   tasks:
     - name: compile
@@ -6442,8 +6454,9 @@ buildvariants:
   - rhel80-zseries-test
   batchtime: 120 # 2 hours
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     # Use half number of vCPU to avoid OOM kill failure
-    smp_command: -j $(echo $(grep -c ^processor /proc/cpuinfo) / 2 | bc)
+    num_threads: -j $(echo $(grep -c ^processor /proc/cpuinfo) / 2 | bc)
   tasks:
     - name: compile
     - name: unit-test
@@ -6458,8 +6471,7 @@ buildvariants:
   - ubuntu2004-arm64-small
   batchtime: 1440 # 24 hours
   expansions:
-    enable_tcmalloc: true
-    smp_command: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_threads: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
   tasks:
     - name: compile
     - name: make-check-test
@@ -6495,9 +6507,8 @@ buildvariants:
   - amazon2-arm64-small
   batchtime: 1440 # 24 hours
   expansions:
-    smp_command: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_threads: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
     cmake_generator: "Unix Makefiles"
-    enable_tcmalloc: true
   tasks:
     - name: compile
     - name: make-check-test
@@ -6527,7 +6538,7 @@ buildvariants:
   run_on:
   - ubuntu2004-test
   expansions:
-    posix_configure_flags: -DENABLE_ANTITHESIS=1 -DENABLE_STRICT=0
+    posix_configure_flags: -DENABLE_TCMALLOC=0 -DENABLE_ANTITHESIS=1 -DENABLE_STRICT=0
     CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/mongodbtoolchain_stable_clang.cmake
   tasks:
     - name: ".antithesis"
@@ -6540,8 +6551,9 @@ buildvariants:
   - ubuntu2004-small
   batchtime: 720 # 12 hours
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
-    smp_command: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_threads: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
   tasks:
     - name: compile
     - name: make-check-test
@@ -6567,8 +6579,9 @@ buildvariants:
   - ubuntu2004-arm64-small
   batchtime: 720 # 12 hours
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
-    smp_command: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_threads: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
   tasks:
     - name: compile
     - name: make-check-test
@@ -6594,8 +6607,8 @@ buildvariants:
   - ubuntu2004-test
   batchtime: 1440 # 24 hours
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
-    enable_tcmalloc: true
   tasks:
     - name: ".stress-test-1"
     - name: ".stress-test-2"
@@ -6614,8 +6627,8 @@ buildvariants:
   - ubuntu2004-arm64-large
   batchtime: 1440 # 24 hours
   expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
-    enable_tcmalloc: true
   tasks:
     - name: ".stress-test-1"
     - name: ".stress-test-2"
