Create initial TSAN infrastructure + add TSAN fail file

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -875,6 +875,18 @@ functions:
             ../tools/pytest_parallel --python $py $threads_command ${unit_test_parallel_args|-v 2} ${unit_test_variant_args} -- $(cat $do_run) 2>&1
         fi
 
+  "tsan warning metric":
+    command: shell.exec
+    params:
+      working_dir: "wiredtiger"
+      shell: bash
+      script: |
+        set -o errexit
+        set -o verbose
+        ${PREPARE_PATH}
+        # Track warnings only after time 2025-08-06 06:07:50.655735+00:00
+        python3 test/evergreen/tsan_warnings_analysis.py --timestamp 1754460496
+
   "code coverage analysis":
     command: shell.exec
     params:
@@ -2216,6 +2228,29 @@ tasks:
       - func: "unit test"
         vars:
           unit_test_args: -v 2 -R cursor13 schema03 timestamp22
+
+  - name: unit-test-tsan
+    tags: ["python"]
+    depends_on:
+    - name: compile
+    commands:
+      - command: timeout.update
+        params:
+          timeout_secs: 86400
+          exec_timeout_secs: 86400
+      - func: "fetch artifacts"
+      - func: "unit test parallel"
+        vars:
+          check_coverage: true
+          # As leader, run the set of tests that are not in the fail list.
+          unit_test_parallel_ignore: test/suite/tsan.fail
+          # The timeout for this command is on a test file basis. Make the timeouts long,
+          # as there are a few files that contain a large number of slower tests.
+          unit_test_parallel_args: -v 2 --timeout 300
+      - func: "upload artifact"
+        vars:
+          upload_source_dir: "wiredtiger"
+          upload_filename: unit-test-tsan.tgz
 
   - name: unit-test-hook-disagg-leader
     tags: ["python"]
@@ -4417,19 +4452,17 @@ tasks:
           test-name: modularity_metrics
           collection: CodeModularityMetrics
 
-  - name: tsan-warning-metrics
+  - name: generate-tsan-metric
+    tags: ["pull_request_code_statistics"]
+    depends_on:
+      - name: "unit-test-tsan"
     commands:
       - func: "get project"
-      - func: "compile wiredtiger"
-      - command: shell.exec
-        params:
-          working_dir: "wiredtiger/cmake_build"
-          shell: bash
-          script: |
-            set -o errexit
-            set -o verbose
-            ${PREPARE_TEST_ENV}
-            python3 ../test/evergreen/tsan_warnings_analysis.py
+      - func: "fetch artifacts"
+        vars:
+          dependent_task: unit-test-tsan
+          destination: wiredtiger/unit-test-tsan
+      - func: "tsan warning metric"
 
     ###############################
     # Performance Tests for btree #
@@ -5788,7 +5821,7 @@ buildvariants:
     num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: examples-c-test
-    - name: tsan-warning-metrics
+    - name: generate-tsan-metric
       batchtime: 10080 # 7 days
 
 # FIXME-WT-13256
@@ -6603,16 +6636,19 @@ buildvariants:
 - name: amazon2023-armv9-tsan
   display_name: "(ARMV9) Amazon Linux 2023 TSAN"
   run_on:
-  - amazon2023-arm64-latest-small-m8g
+  - amazon2023-arm64-latest-large-m8g
   expansions:
     CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/mongodbtoolchain_stable_clang.cmake
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=TSan
     ENABLE_TCMALLOC: 0
     additional_env_vars: |
-      export TSAN_OPTIONS="$COMMON_SAN_OPTIONS:history_size=7:print_suppressions=0:suppressions=$(git rev-parse --show-toplevel)/test/evergreen/tsan_warnings.supp"
-    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+      export TSAN_OPTIONS="$COMMON_SAN_OPTIONS:history_size=2:print_suppressions=0:suppressions=$(git rev-parse --show-toplevel)/test/evergreen/tsan_warnings.supp:log_path=$(git rev-parse --show-toplevel)/tsan_logs:exitcode=0"
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo` / 8" | bc)
   tasks:
+    - name: compile
     - name: examples-c-test
+    - name: unit-test-tsan
+    - name: generate-tsan-metric
 
 - name: amazon2023-armv9-msan
   display_name: "(ARMV9) Amazon Linux 2023 MSAN"
