Removing unnecessary redirect of stderr to stdout.

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -559,7 +559,7 @@ functions:
       script: |
         set -o errexit
         set -o verbose
-        # Fail, showing the configuration file.
+        # Fail, show the configuration file.
         fail() {
           echo "======= FAILURE =========="
           [ -f RUNDIR/CONFIG ] && cat RUNDIR/CONFIG
@@ -567,7 +567,7 @@ functions:
         }
 
         for i in $(seq ${times|1}); do
-          ./t -c ${config|../../../test/format/CONFIG.stress} ${trace_args|-T bulk,txn,retain=50} ${extra_args|} || fail 2>&1
+          ./t -c ${config|../../../test/format/CONFIG.stress} ${trace_args|-T bulk,txn,retain=50} ${extra_args|} || fail
         done
   "format test predictable":
     command: shell.exec
