WT-16482 Disable reopening db in multi-node

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -1072,7 +1072,9 @@ functions:
           echo Iteration $i/${times}
           rm -rf RUNDIR
           ./t -c ../../../test/format/CONFIG.disagg ${format_args|} ${extra_arg|} || fail
-          ./t -R $format_args ${extra_args|} || fail
+          if [ ${reopen|true} = true ]; then
+            ./t -R $format_args ${extra_args|} || fail
+          fi
         done
   "many dbs test":
     command: shell.exec
@@ -1691,6 +1693,7 @@ variables:
         vars:
           format_args: disagg.multi=1 runs.predictable_replay=1 runs.ops=500000:2000000
           times: 5
+          reopen: false # FIXME-WT-16135 Reopen currently causes failures in disagg multi mode.
 
   - &format-stress-test-disagg-multi-data-validation
     depends_on:
@@ -1702,6 +1705,7 @@ variables:
           # Validate data with a non-layered table.
           format_args: disagg.multi=1 runs.predictable_replay=1 ops.verify=1 disagg.multi_validation=1 runs.ops=500000:2000000
           times: 5
+          reopen: false # FIXME-WT-16135 Reopen currently causes failures in disagg multi mode.
 
 #######################################
 #               Tasks                 #
