Initial move to two new standalone variants

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -662,9 +662,9 @@ functions:
           threads_command="-j ${num_jobs}"
         fi
         if [ ${check_coverage|false} = true ]; then
-            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} $threads_command 2>&1 || echo "Ignoring failed test as we are checking test coverage"
+            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} ${unit_test_hook} $threads_command 2>&1 || echo "Ignoring failed test as we are checking test coverage"
         else
-            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} $threads_command 2>&1
+            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} ${unit_test_hook} $threads_command 2>&1
         fi
 
   "code coverage analysis":
@@ -1552,7 +1552,7 @@ tasks:
 
   # Base compile for nonstandalone build
   - name: compile-nonstandalone
-    tags: ["pull_request"]
+    tags: ["pull_request", "nonstandalone"]
     commands:
       - func: "get project"
       - func: "compile wiredtiger"
@@ -2553,151 +2553,6 @@ tasks:
       - func: "unit test"
         vars:
           unit_test_args: -v 2 -b 11/12
-
-  - name: unit-test-nonstandalone-bucket00
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 0/12
-
-  - name: unit-test-nonstandalone-bucket01
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 1/12
-
-  - name: unit-test-nonstandalone-bucket02
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 2/12
-
-  - name: unit-test-nonstandalone-bucket03
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 3/12
-
-
-  - name: unit-test-nonstandalone-bucket04
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 4/12
-
-  - name: unit-test-nonstandalone-bucket05
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 5/12
-
-  - name: unit-test-nonstandalone-bucket06
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 6/12
-
-  - name: unit-test-nonstandalone-bucket07
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 7/12
-
-  - name: unit-test-nonstandalone-bucket08
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 8/12
-
-  - name: unit-test-nonstandalone-bucket09
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 9/12
-
-  - name: unit-test-nonstandalone-bucket10
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 10/12
-
-  - name: unit-test-nonstandalone-bucket11
-    tags: ["python", "pull_request"]
-    depends_on:
-    - name: compile-nonstandalone
-    commands:
-      - func: "fetch artifacts"
-        vars:
-          dependent_task: compile-nonstandalone
-      - func: "unit test"
-        vars:
-          unit_test_args: --hook nonstandalone -v 2 -b 11/12
 
   - name: unit-test-long-bucket00
     tags: ["python", "unit_test_long"]
@@ -5931,11 +5786,6 @@ buildvariants:
     - name: s3-tiered-storage-extensions-test
     - name: azure-gcp-tiered-storage-extensions-test
     - name: bench-tiered-push-pull
-    - name: compile-nonstandalone
-    - name: make-check-nonstandalone
-    - name: unit-test-extra-long-nonstandalone
-      distros: ubuntu2004-large
-    - name: ".data-validation-stress-test-nonstandalone"
     - name: catch2-unittest-assertions
     - name: ".tiered_unittest"
     - name: bench-tiered-push-pull-s3
@@ -6077,12 +5927,6 @@ buildvariants:
       run_on:
       - ubuntu2004-medium
     - name: format-abort-recovery-stress-test
-    - name: ".stress-test-1-nonstandalone"
-    - name: ".stress-test-2-nonstandalone"
-    - name: ".stress-test-3-nonstandalone"
-    - name: ".stress-test-4-nonstandalone"
-    - name: ".stress-test-no-barrier-nonstandalone"
-    - name: format-abort-recovery-stress-test-nonstandalone
     - name: format-predictable-test
     # FIXME-WT-10822
     # - name: format-tiered-test
@@ -6125,9 +5969,7 @@ buildvariants:
     num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: compile
-    - name: compile-nonstandalone
     - name: ".cppsuite-stress-test"
-    - name: ".cppsuite-stress-test-nonstandalone"
 
 - name: cppsuite-stress-tests-arm64
   display_name: "Cppsuite Stress Tests ARM64"
@@ -6398,9 +6240,6 @@ buildvariants:
     - name: configure-combinations
     - name: format-smoke-test
     - name: s3-tiered-storage-extensions-test
-    - name: compile-nonstandalone
-    - name: make-check-nonstandalone
-    - name: unit-test-nonstandalone
 
 - name: ubuntu2004-release-arm64
   display_name: "~ Ubuntu 20.04 (ARM64, Release Build)"
@@ -6444,9 +6283,6 @@ buildvariants:
     - name: ".stress-test-2"
     - name: ".stress-test-sanitizer"
     - name: format-abort-recovery-stress-test
-    - name: ".stress-test-1-nonstandalone"
-    - name: ".stress-test-2-nonstandalone"
-    - name: format-abort-recovery-stress-test-nonstandalone
     - name: format-predictable-test
 
 # When running the Python tests on this variant tcmalloc must be preloaded otherwise the wiredtiger library
@@ -6464,6 +6300,60 @@ buildvariants:
     - name: ".stress-test-1"
     - name: ".stress-test-2"
     - name: format-abort-recovery-stress-test
+
+- name: ubuntu2004-nonstandalone
+  display_name: "Ubuntu 20.04 Nonstandalone"
+  run_on:
+  - ubuntu2004-test
+  expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
+    data_validation_stress_test_args: -t r -m -W 3 -D -p -n 100000 -k 100000 -C cache_size=100MB
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    NONSTANDALONE: -DWT_STANDALONE_BUILD=0
+    unit_test_hook: --hook nonstandalone
+  tasks:
+    - name: ".pull_request !.pull_request_compilers"
+    - name: compile
+    - name: make-check-nonstandalone
+    - name: unit-test-extra-long
+      distros: ubuntu2004-large
+    - name: ".data-validation-stress-test-nonstandalone"
+  
+- name: ubuntu2004-nonstandalone-stress
+  display_name: "Ubuntu 20.04 Nonstandalone Stress"
+  run_on:
+  - ubuntu2004-test
+  expansions:
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    NONSTANDALONE: -DWT_STANDALONE_BUILD=0
+  tasks:
     - name: ".stress-test-1-nonstandalone"
     - name: ".stress-test-2-nonstandalone"
+    - name: ".stress-test-3-nonstandalone"
+    - name: ".stress-test-4-nonstandalone"
+    - name: ".stress-test-no-barrier-nonstandalone"
     - name: format-abort-recovery-stress-test-nonstandalone
+    - name: ".cppsuite-stress-test-nonstandalone"
+      distros: ubuntu2004-medium
+    - name: ".stress-test-1-nonstandalone"
+      vars:
+        CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
+    - name: ".stress-test-2-nonstandalone"
+      vars:
+        CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
+    - name: format-abort-recovery-stress-test-nonstandalone
+      vars:
+        CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
+    - name: compile-nonstandalone
+      vars:
+        CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
+    - name: make-check-nonstandalone
+      vars:
+        CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
+    - name: unit-test-nonstandalone
+      vars:
+        CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
+
+      
+    
