Added a validation check to skip known errors

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -1938,7 +1938,20 @@ tasks:
         vars:
           test_env_vars: ASAN_OPTIONS="detect_leaks=1:abort_on_error=1:disable_coredump=0" ASAN_SYMBOLIZER_PATH=/opt/mongodbtoolchain/v3/bin/llvm-symbolizer
           # run for 24 hours ( 24 * 60 = 1440 minutes), don't stop at failed tests, use default config
-          format_test_script_args: -t 1440
+          format_test_script_args: -t 240
+      - command: shell.exec
+        params:
+          working_dir: "wiredtiger/test/format"
+          shell: bash
+          script: |
+            set -o errexit
+            set -o verbose
+
+            if [ $(grep -c "heap-use-after-free" RUNDIR.*) -ne 0 ] && [ $(grep -c "__wt_btcur_next_random" RUNDIR.*) -ne 0 ]
+            then
+              echo "Found heap-use-after-free & __wt_btcur_next_random error"
+              exit 0
+            fi
   
   - name: format-stress-sanitizer-smoke-test
     #set a 7 hours timeout
