Address PR changes pt.2

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -273,9 +273,9 @@ functions:
           # Compiling with CMake generated Ninja file.
           cd cmake_build
           if [ "${cmake_generator|Ninja}" = "Ninja" ]; then
-            ninja ${num_parallel} 2>&1
+            ninja -j ${num_jobs} 2>&1
           else
-            make ${num_parallel} 2>&1
+            make -j ${num_jobs} 2>&1
           fi
         fi
         echo "Ending 'make wiredtiger' step"
@@ -396,7 +396,7 @@ functions:
               pushd cmake_build
               # Adding -DENABLE_PYTHON=1 -DENABLE_STRICT=1 as 6.0 does not default these like develop.
               $CMAKE -DCMAKE_C_FLAGS="-DMIGHT_NOT_RUN -Wno-error" -DENABLE_PYTHON=1 -DENABLE_STRICT=1 ../.
-              make -C lang/python ${num_parallel}
+              make -C lang/python -j ${num_jobs}
             fi
             # Pop to root project directory.
             popd
@@ -486,8 +486,8 @@ functions:
         ${PREPARE_TEST_ENV}
         . test/evergreen/find_cmake.sh
         cd cmake_build
-        echo "Using number of parallel processes '${num_parallel}' for 'make check all'"
-        $CTEST -L check ${num_parallel} --output-on-failure ${check_args|} 2>&1
+        echo "Using number of parallel processes '-j ${num_jobs}' for 'make check all'"
+        $CTEST -L check -j ${num_jobs} --output-on-failure ${check_args|} 2>&1
 
   "cppsuite test":
     - command: shell.exec
@@ -590,11 +590,11 @@ functions:
         set -o verbose
         ${PREPARE_TEST_ENV}
         cd cmake_build
-        echo "Using num_parallel '${num_parallel}' for 'unit test'"
+        echo "Using num_jobs '-j ${num_jobs}' for 'unit test'"
         if [ ${check_coverage|false} = true ]; then
-            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} ${num_parallel} 2>&1 || echo "Ignoring failed test as we are checking test coverage"
+            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} -j ${num_jobs} 2>&1 || echo "Ignoring failed test as we are checking test coverage"
         else
-            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} ${num_parallel} 2>&1
+            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} -j ${num_jobs} 2>&1
         fi
 
   "code coverage analysis":
@@ -728,7 +728,7 @@ functions:
         ${PREPARE_TEST_ENV}
         ${format_test_setting|}
         for i in $(seq ${times|1}); do
-          ./format.sh ${num_parallel} ${format_test_script_args|} 2>&1
+          ./format.sh -j ${num_jobs} ${format_test_script_args|} 2>&1
         done
   "format test tiered":
     command: shell.exec
@@ -1252,7 +1252,7 @@ variables:
       # We'll explicitly use the python3 in /usr/bin, we use the same in configuring cmake.
       CMAKE_TOOLCHAIN_FILE:
       CC_OPTIMIZE_LEVEL: -DCC_OPTIMIZE_LEVEL=-O0
-      num_parallel: -j $(echo $(sysctl -n hw.logicalcpu) / 2 | bc)
+      num_jobs: $(echo $(sysctl -n hw.logicalcpu) / 2 | bc)
       cmake_generator: "Unix Makefiles"
       additional_env_vars: |
         export LD_LIBRARY_PATH=""
@@ -2647,7 +2647,7 @@ tasks:
             set -o errexit
             set -o verbose
             ${PREPARE_TEST_ENV}
-            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} --hook tiered=tier_storage_source='s3_store' ${num_parallel} 2>&1
+            ${python_binary|python3} ../test/suite/run.py ${unit_test_args|-v 2} --hook tiered=tier_storage_source='s3_store' -j ${num_jobs} 2>&1
 
   - name: unit-test-hook-tiered-timestamp
     tags: ["python"]
@@ -4353,7 +4353,7 @@ tasks:
             set -o errexit
             set -o verbose
             ${PREPARE_TEST_ENV}
-            ./run_format_configs.sh ${num_parallel}
+            ./run_format_configs.sh -j ${num_jobs}
 
   - name: static-wt-build-test
     commands:
@@ -6078,7 +6078,7 @@ buildvariants:
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
     data_validation_stress_test_args: -t r -m -W 3 -D -p -n 100000 -k 100000 -C cache_size=100MB
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
   tasks:
     - name: ".pull_request !.pull_request_compilers"
     - name: ".unit_test_long"
@@ -6136,7 +6136,7 @@ buildvariants:
     additional_env_vars: |
       export LSAN_OPTIONS="$COMMON_SAN_OPTIONS:print_suppressions=0:suppressions=$(git rev-parse --show-toplevel)/test/evergreen/asan_leaks.supp"
       export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libeatmydata.so:$LD_PRELOAD"  
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: ".pull_request !.pull_request_compilers !.python !.tiered_unittest"
     - name: examples-c-test
@@ -6152,7 +6152,7 @@ buildvariants:
     ENABLE_CPPSUITE: -DENABLE_CPPSUITE=0 
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     posix_configure_flags: -DENABLE_PYTHON=0 -DENABLE_LZ4=0 -DENABLE_SNAPPY=0 -DENABLE_ZLIB=0 -DENABLE_ZSTD=0
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: compile
     - name: make-check-test
@@ -6170,14 +6170,14 @@ buildvariants:
     # Use optimisation level -O0 since Clang treats -Og (our default optimisation for non-release 
     # builds) as -O1, making test binaries more difficult to debug. 
     CC_OPTIMIZE_LEVEL: -DCC_OPTIMIZE_LEVEL=-O0
-    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     additional_env_vars: |
       export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libeatmydata.so:$LD_PRELOAD"
     # We don't run C++ memory sanitized testing as it creates false positives. MSAN also causes
     # some csuite tests to take an extended amount of time. These are excluded from the 
     # make-check-test task and are covered by the csuite-long-running task.
     check_args: -LE "cppsuite|long_running"
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: clang-analyzer
     - name: compile
@@ -6204,7 +6204,7 @@ buildvariants:
     CC_OPTIMIZE_LEVEL: -DCC_OPTIMIZE_LEVEL=-O0
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
     additional_env_vars: export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libeatmydata.so
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: clang-analyzer
     - name: compile
@@ -6225,7 +6225,7 @@ buildvariants:
   - ubuntu2004-wt-build
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: ".pull_request_compilers"
 
@@ -6236,7 +6236,7 @@ buildvariants:
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
     additional_env_vars: export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libeatmydata.so:$LD_PRELOAD"
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     # FIXME-WT-11606 Remove this temporary task.
     - name: format-11507-test
@@ -6271,7 +6271,7 @@ buildvariants:
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
     additional_env_vars: export LD_PRELOAD="/usr/lib/aarch64-linux-gnu/libeatmydata.so:$LD_PRELOAD"
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     # FIXME-WT-11606 Remove this temporary task.
     - name: format-11507-test
@@ -6295,7 +6295,8 @@ buildvariants:
   # We run on medium as small has too small a disk.
   - ubuntu2004-medium
   expansions:
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: compile
     - name: compile-nonstandalone
@@ -6309,7 +6310,7 @@ buildvariants:
   - ubuntu2004-arm64-large
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: compile
     - name: compile-nonstandalone
@@ -6332,7 +6333,7 @@ buildvariants:
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     additional_env_vars: export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libeatmydata.so:$LD_PRELOAD"
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: compile-linux-no-ftruncate
     - name: make-check-linux-no-ftruncate-test
@@ -6348,7 +6349,7 @@ buildvariants:
     additional_env_vars: export LD_PRELOAD="/usr/local/lib/libeatmydata.so:$LD_PRELOAD"
     cmake_generator: "Unix Makefiles"
     CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/gcc.cmake
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: compile
     - name: make-check-test
@@ -6429,7 +6430,7 @@ buildvariants:
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     posix_configure_flags: -DENABLE_ZSTD=0
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: compile
     - name: generate-datafile-big-endian
@@ -6445,7 +6446,7 @@ buildvariants:
     format_test_setting: ulimit -c unlimited
     CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/mongodbtoolchain_stable_clang.cmake
     # Use quarter of the vCPUs to avoid OOM kill failure and disk issues on this variant.
-    num_parallel: -j $(echo $(grep -c ^processor /proc/cpuinfo) / 4 | bc)
+    num_jobs: $(echo $(grep -c ^processor /proc/cpuinfo) / 4 | bc)
     ENABLE_CPPSUITE: -DENABLE_CPPSUITE=0
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     posix_configure_flags: -DENABLE_STRICT=0
@@ -6466,7 +6467,7 @@ buildvariants:
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     # Use half number of vCPU to avoid OOM kill failure
-    num_parallel: -j $(echo $(grep -c ^processor /proc/cpuinfo) / 2 | bc)
+    num_jobs: $(echo $(grep -c ^processor /proc/cpuinfo) / 2 | bc)
   tasks:
     - name: compile
     - name: unit-test
@@ -6482,7 +6483,7 @@ buildvariants:
   batchtime: 1440 # 24 hours
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
   tasks:
     - name: compile
     - name: make-check-test
@@ -6519,7 +6520,7 @@ buildvariants:
   batchtime: 1440 # 24 hours
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
     cmake_generator: "Unix Makefiles"
   tasks:
     - name: compile
@@ -6553,7 +6554,7 @@ buildvariants:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0 
     posix_configure_flags: -DENABLE_ANTITHESIS=1 -DENABLE_STRICT=0
     CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/mongodbtoolchain_stable_clang.cmake
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: ".antithesis"
       cron: 0 0 * * 4 # once a week (Thursday midnight UTC)
@@ -6567,7 +6568,7 @@ buildvariants:
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
   tasks:
     - name: compile
     - name: make-check-test
@@ -6595,7 +6596,7 @@ buildvariants:
   expansions:
     ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo` * 2" | bc)
   tasks:
     - name: compile
     - name: make-check-test
@@ -6621,9 +6622,9 @@ buildvariants:
   - ubuntu2004-test
   batchtime: 1440 # 24 hours
   expansions:
-    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: ".stress-test-1"
     - name: ".stress-test-2"
@@ -6642,9 +6643,9 @@ buildvariants:
   - ubuntu2004-arm64-large
   batchtime: 1440 # 24 hours
   expansions:
-    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=0
+    ENABLE_TCMALLOC: -DENABLE_TCMALLOC=1
     CMAKE_BUILD_TYPE: -DCMAKE_BUILD_TYPE=RelWithDebInfo
-    num_parallel: -j $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
+    num_jobs: $(echo "`grep -c ^processor /proc/cpuinfo`" | bc)
   tasks:
     - name: ".stress-test-1"
     - name: ".stress-test-2"
