Added a new generic script to skip known errors

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -1944,26 +1944,22 @@ tasks:
             ASAN_OPTIONS="detect_leaks=1:abort_on_error=1:disable_coredump=0" ASAN_SYMBOLIZER_PATH=/opt/mongodbtoolchain/v3/bin/llvm-symbolizer
 
             # run for 24 hours ( 24 * 60 = 1440 minutes), don't stop at failed tests, use default config
-            ${test_env_vars|} ${format_test_setting|} ./format.sh ${smp_command|} -t 200 2>&1
+            ${test_env_vars|} ${format_test_setting|} ./format.sh ${smp_command|} -t 300 2>&1
             format_ret=$?
 
             # If any of the format job fails i.e, format.sh script returns 1 then we need to check if
             # it failed with any of the known errors.
-
-            # Known errors to be skipped are
-            # *  heap-use-after-free && __wt_btcur_next_random
-
             if [ $format_ret -ne 0 ]
             then
-              echo "There are some failed jobs."
-              ret=`grep -q "heap-use-after-free" RUNDIR.*.log && grep "__wt_btcur_next_random" RUNDIR.*.log | wc -l`
-              if [ "$ret" != 0 ]
+              # Call the generic format skip error script to skip known errors
+              ./format_skip_errors.sh
+              if [ $? -eq 0 ]
               then
-                echo "Found heap-use-after-free & __wt_btcur_next_random error"
                 exit 0
               fi
             fi
 
+            # Propogate the exit status of format script.
             exit $format_ret
   
   - name: format-stress-sanitizer-smoke-test
