WT-5334 Add testing coverage for static wt build (#5096)
* Added a new task static-wt-build-test which tests if the wt binary is statically linked

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -2067,6 +2067,39 @@ tasks:
             cp ../../../bench/wtperf/split_heavy.wtperf .
             ./wtperf -O ./split_heavy.wtperf -o verbose=2
 
+  - name: static-wt-build-test
+    commands:
+      - func: "get project"
+      - func: "compile wiredtiger"
+        vars:
+          posix_configure_flags: --disable-shared --with-builtins=snappy,zlib
+      - command: shell.exec
+        params:
+          working_dir: "wiredtiger/build_posix"
+          shell: bash
+          script: |
+            set -o errexit
+            set -o verbose
+
+            # Delete wt util
+            rm -f wt
+            # Build static wt util
+            make CC='eval "g++ -static"' ${smp_command|}
+            # -V option displays Wiredtiger library version
+            ./wt -V
+
+            if [ $? -ne 0 ]; then
+              echo "Error, WT util is not generated or is not functioning"
+              exit 1
+            fi
+
+            ldd wt || wt_static_build=1
+
+            if [ $wt_static_build -ne 1 ]; then
+              echo "Error, WT util is not statically linked"
+              exit 1
+            fi
+
 buildvariants:
 - name: ubuntu1804
   display_name: Ubuntu 18.04
@@ -2103,6 +2136,7 @@ buildvariants:
     - name: format-stress-test
     - name: format-stress-smoke-test
     - name: checkpoint-stress-test
+    - name: static-wt-build-test
 
 - name: ubuntu1804-compilers
   display_name: Ubuntu 18.04 Compilers
