Show more information on evergreen failures. Refactor evergreen shell scripts.

diff --git a/test/evergreen.yml b/test/evergreen.yml
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -485,35 +485,40 @@ functions:
         # replay using the same data seed, should guarantee we have equivalent data created.
         set -o errexit
         set -o verbose
+        fail() {
+          echo "======= FAILURE =========="
+          for file do:
+            if [ -f "$file" ]; then
+              echo Contents of "$file":
+              cat "$file"
+              echo "================"
+            fi
+          done
+          exit 1
+        }
         runtime=3  # minutes
         config=../../../test/format/CONFIG.replay
         for i in $(seq ${times}); do
           echo Iteration $i/${times}
           x2=$RANDOM$RANDOM
           x3=$RANDOM$RANDOM
-          rm -rf RUNDIR RUNDIR_{1,2,3}
+          rm -rf RUNDIR_{1,2,3}
 
           first_run_args="-c $config runs.timer=$runtime"
-          ./t $first_run_args ${extra_args} || ( [ -f RUNDIR/CONFIG ] && cat RUNDIR/CONFIG ) 2>&1
+          ./t -h RUNDIR_1 $first_run_args ${extra_args} || fail RUNDIR_1/CONFIG 2>&1
+          stable_hex=$(../../../tools/wt_timestamps RUNDIR_1 | sed -e '/stable=/!d' -e 's/.*=//')
+          ops=$(echo $((0x$stable_hex)))
 
-          if [ -f RUNDIR/CONFIG ]; then
-            mv RUNDIR RUNDIR_1
-            stable_hex=$(../../../tools/wt_timestamps RUNDIR_1 | sed -e '/stable=/!d' -e 's/.*=//')
-            ops=$(echo $((0x$stable_hex)))
+          # Do the second run up to the stable timestamp, using the same data seed,
+          # but with a different extra seed.  Compare it when done.
+          common_args="-c RUNDIR_1/CONFIG runs.timer=0 runs.ops=$ops"
+          ./t -h RUNDIR_2 $common_args random.extra_seed=$x2 || fail RUNDIR_2/CONFIG 2>&1
+          ../../../tools/wt_cmp_dir RUNDIR_1 RUNDIR_2 || fail RUNDIR_1/CONFIG RUNDIR_2/CONFIG 2>&1
 
-            # Do the second run up to the stable timestamp, using the same data seed,
-            # but with a different extra seed.  Compare it when done.
-            common_args="-c RUNDIR_1/CONFIG runs.timer=0 runs.ops=$ops"
-            ./t $common_args random.extra_seed=$x2 || ( [ -f RUNDIR/CONFIG ] && cat RUNDIR/CONFIG ) 2>&1
-            mv RUNDIR RUNDIR_2
-            ../../../tools/wt_cmp_dir RUNDIR_1 RUNDIR_2
-
-            # Do the third run up to the stable timestamp, using the same data seed,
-            # but with a different extra seed.  Compare it to the second run when done.
-            ./t $common_args random.extra_seed=$x3 || ( [ -f RUNDIR/CONFIG ] && cat RUNDIR/CONFIG ) 2>&1
-            mv RUNDIR RUNDIR_3
-            ../../../tools/wt_cmp_dir RUNDIR_2 RUNDIR_3
-          fi
+          # Do the third run up to the stable timestamp, using the same data seed,
+          # but with a different extra seed.  Compare it to the second run when done.
+          ./t -h RUNDIR_3 $common_args random.extra_seed=$x3 || fail RUNDIR_3/CONFIG 2>&1
+          ../../../tools/wt_cmp_dir RUNDIR_2 RUNDIR_3 || fail RUNDIR_2/CONFIG RUNDIR_3/CONFIG 2>&1
         done
   "format test script":
     command: shell.exec
