Do not rely on S3 to download the clang-format binary

diff --git a/dist/s_clang_format b/dist/s_clang_format
--- a/dist/s_clang_format
+++ b/dist/s_clang_format
@@ -5,29 +5,6 @@ set -o pipefail
 t=__wt.$$
 trap 'rm -rf $t' 0 1 2 3 13 15
 
-download_clang_format() {
-    version=$1
-    # FIXME-WT-10583
-    arch=$(uname -m)
-    if [ ! "$arch" = "x86_64" ]; then
-        echo "$0: unsupported architecture $arch to run clang_format"
-        return 1
-    fi
-
-    archive=dist/clang-format.tar.gz
-    sys_os=$(uname)
-    if [ "$sys_os" = "Linux" ]; then
-        curl https://s3.amazonaws.com/boxes.10gen.com/build/clang-format-llvm-"$version"-x86_64-linux-gnu-ubuntu-20.04.tar-1.gz -o $archive
-        tar --strip=1 -C dist/ -xf $archive clang-format-llvm-"$version"-x86_64-linux-gnu-ubuntu-20.04/clang-format && rm $archive
-    elif [ "$sys_os" = "Darwin" ]; then
-        curl https://s3.amazonaws.com/boxes.10gen.com/build/build/clang-format-llvm-"$version"-x86_64-apple-darwin.tar.gz -o $archive
-        tar --strip=1 -C dist/ -xf $archive clang-format-llvm-"$version"-x86_64-apple-darwin/clang-format && rm $archive
-    else
-        echo "$0: unsupported environment $sys_os"
-        return 1
-    fi
-}
-
 # Find the top-level WiredTiger directory.
 dest_dir=$(git rev-parse --show-toplevel)
 
@@ -44,15 +21,10 @@ export PATH="${PWD}/dist":$PATH
 
 # Check if Clang-Format is already available with the desired version.
 desired_version="10.0.0"
-if ! command -v clang-format &> /dev/null; then
-    download_clang_format $desired_version || exit 1
-elif ! clang-format --version | grep -q $desired_version; then
-    download_clang_format $desired_version || exit 1
+if ! command -v clang-format &> /dev/null || ! clang-format --version | grep -q $desired_version; then
+    echo "Failed to find Clang-Format, make sure the binary (version: $desired_version) is in your env PATH."
+    exit 1
 fi
-
-# Users may need to manually approve binaries.
-# If we're not allowed to run Clang-Format, let's exit (should be obvious from the dialog).
-clang-format --version &> /dev/null || exit 1
 
 exclude=true
 case $# in
