Fix indentation.

diff --git a/dist/s_clang-format b/dist/s_clang-format
--- a/dist/s_clang-format
+++ b/dist/s_clang-format
@@ -21,8 +21,8 @@ test "$p" != "/" || {
 clang_format_version="6.0.0"
 clang-format --version | grep "version $clang_format_version" >/dev/null 2>&1
 if test $? -ne 0; then
-    echo "$0: found incorrect version of clang-format ($clang_format_version required)"
-    exit 1
+	echo "$0: found incorrect version of clang-format ($clang_format_version required)"
+	exit 1
 fi
 
 cd $p || exit 1
