WT-4658 Support downloading Clang Format from S3.

diff --git a/dist/s_clang-format b/dist/s_clang-format
--- a/dist/s_clang-format
+++ b/dist/s_clang-format
@@ -1,18 +1,30 @@
 #! /bin/sh
 
-# Installation of the clang development package isn't standard, list a
-# couple of the places we're using.
-export PATH=$PATH:/usr/local/clang60/bin:/usr/local/llvm-devel/bin
+download_clang_format() {
+	echo "$0: downloading clang-format for $(uname)"
+	if [ `uname` = "Linux" ]; then
+		wget https://s3.amazonaws.com/boxes.10gen.com/build/clang-format-3.8-rhel55.tar.gz -O dist/clang-format.tar.gz
+	elif [ `uname` = "Darwin" ]; then
+		wget https://s3.amazonaws.com/boxes.10gen.com/build/clang%2Bllvm-3.8.0-x86_64-apple-darwin.tar.xz dist/clang-format.tar.gz
+	else
+		echo "$0: unsupported environment"
+		exit 1
+	fi
+	tar --strip=2 -C dist/ -xf dist/clang-format.tar.gz build/bin/clang-format
+}
 
 # Find the top-level WiredTiger directory and move to there.
 cd `git rev-parse --show-toplevel` || exit 1
 
+# Override existing Clang Format versions in the PATH.
+export PATH="${PWD}/dist":$PATH
+
 # Ensure that we have the correct version of clang-format.
-clang_format_version="6.0.0"
+clang_format_version="3.8.0"
 clang-format --version | grep "version $clang_format_version" >/dev/null 2>&1
 if test $? -ne 0; then
-	echo "$0: found incorrect version of clang-format ($clang_format_version required)"
-	exit 1
+	echo "$0: incorrect/missing version of clang-format ($clang_format_version required)"
+	download_clang_format
 fi
 
 case $# in
