Don't exit non-zero unless the python script did, the script requires python modules that are commonly not installed, and in that case it exits 0. Post the complaint, but don't fail.

diff --git a/dist/s_evergreen b/dist/s_evergreen
--- a/dist/s_evergreen
+++ b/dist/s_evergreen
@@ -8,12 +8,17 @@ program=${toplevel_dir}/test/evergreen/evg_cfg.py
 
 # Run checking program to identify missing tests in Evergreen configuration
 ${program} check >$t 2>&1
+e=$?
 
 test -s $t && {
 	echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
 	echo "$0: $program check"
-	echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
 	cat $t
-	exit 1
+	echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+
+	# Don't exit non-zero unless the python script did, the script
+	# requires python modules that are commonly not installed, and
+	# in that case it exits 0. Post the complaint, but don't fail.
+	exit $e
 }
 exit 0
