Revert "WT-7437 Upgrade documentation to doxygen 1.8.17 (3.6 backport) (#6614) (#6919)"
This reverts commit 87343e95aee6770350aa3db655adea69d1434e57.

diff --git a/dist/s_export b/dist/s_export
--- a/dist/s_export
+++ b/dist/s_export
@@ -12,10 +12,7 @@ Darwin)
 *)
 	# We require GNU nm, which may not be installed.
 	type nm > /dev/null 2>&1 &&
-	    (nm --version | grep 'GNU nm') > /dev/null 2>&1 || {
-	    echo "$0 skipped: GNU nm not found"
-	    exit 0
-	}
+	    (nm --version | grep 'GNU nm') > /dev/null 2>&1 || exit 0
 	NM='nm --extern-only --defined-only --print-file-name $f | egrep -v "__bss_start|_edata|_end|_fini|_init"'
 	;;
 esac
@@ -54,5 +51,5 @@ for d in .. ../build_posix; do
 	done
 done
 
-echo "$0 skipped: libwiredtiger.[a|so|dylib] not found"
+echo "skipped: libwiredtiger.[a|so|dylib] not found"
 exit 0
