Introducing an s_fast script

diff --git a/dist/s_fast b/dist/s_fast
--- a/dist/s_fast
+++ b/dist/s_fast
@@ -2,39 +2,28 @@
 
 # Run standard scripts.
 t=__wt.$$
-t_pfx=__s_all_tmp_
-trap 'rm -f $t *.pyc __tmp __wt.* __s_all_tmp*' 0 1 2 3 13 15
+t_pfx=__s_fast_tmp_
+trap 'rm -f $t *.pyc __tmp __wt.* __s_all_tmp* __s_fast_tmp*' 0 1 2 3 13 15
 
 # We require python which may not be installed.
 type python > /dev/null 2>&1 || {
-	echo 's_all: python not found'
+	echo 's_fast: python not found'
 	exit 1
 }
 
-echo 'dist/s_all run started...'
+echo 'dist/s_fast run started...'
 
-force=
-reconf=0
 errmode=0
 errfound=0
 while :
 	do case "$1" in
-	-A)	# Reconfigure the library build.
-		reconf=1
-		shift;;
 	-E)	# Return an error code on failure
 		errmode=1
-		shift;;
-	-f)	# Force versions to be updated
-		force="-f"
 		shift;;
 	*)
 		break;;
 	esac
 done
-
-echo "Updating files that include the package version" &&
-    sh ./s_version $force
 
 errchk()
 {
@@ -74,8 +63,6 @@ run()
 
 # Non parallelizable scripts. The following scripts either modify files or
 # already parallelize internally.
-run "sh ./s_readme $force"
-run "sh ./s_install $force"
 run "python api_config_gen.py"
 run "python api_err.py"
 run "python flags.py"
@@ -83,8 +70,8 @@ run "python log.py"
 run "python stat.py"
 run "python verbose.py"
 run "sh ./s_copyright"
-run "sh ./s_style -a"
-run "./s_clang-format -a"
+run "sh ./s_style"
+run "./s_clang-format"
 run "python prototypes.py"
 run "sh ./s_typedef -b"
 run "python test_tag.py"
@@ -133,7 +120,7 @@ for f in `find . -name ${t_pfx}\*`; do
 	fi
 done
 
-echo 'dist/s_all run finished'
+echo 'dist/s_fast run finished'
 if test $errmode -ne 0; then
 	exit $errfound;
 fi
