Check for TODO comments

diff --git a/dist/s_fixme b/dist/s_fixme
--- a/dist/s_fixme
+++ b/dist/s_fixme
@@ -1,8 +1,7 @@
 #! /bin/bash
 
-# Find "fix" comments related to the ticket potentially indicated by the branch name.
-# The script only fails if the branch name follows a specific syntax and "fix" comments are found,
-# otherwise, the script exits without failing.
+# Find "fix" and "todo" comments related to the ticket potentially indicated by the branch name.
+# The script only fails if the branch name follows a specific syntax and those comments are found.
 
 # Retrieve the current branch name.
 branch_name=$(git rev-parse --abbrev-ref HEAD)
@@ -16,9 +15,13 @@ fi
 # Get what could be the ticket id.
 ticket_id=$(echo "$branch_name" | cut -d "-" -f-2)
 
-# Check for "fix" comments related to the ticket left behind.
+# Check for comments related to the ticket.
 if grep -inr --exclude-dir=.git "fix.*$ticket_id" ../. > /dev/null 2>&1; then
     echo "Please fix the comments related to $ticket_id."
+    exit 1
+fi
+if grep -inr --exclude-dir=.git "todo.*$ticket_id" ../. > /dev/null 2>&1; then
+    echo "Please fix the todo comments related to $ticket_id."
     exit 1
 fi
 
