Fixed changes done to setup_spawn_host

diff --git a/test/evergreen/setup_spawn_host b/test/evergreen/setup_spawn_host
--- a/test/evergreen/setup_spawn_host
+++ b/test/evergreen/setup_spawn_host
@@ -1,58 +1,58 @@
 #!/bin/bash
-
-archive_fail() {
-    echo "Error: archive [${1}] not found." >&2
-}
-
-cd $HOME # workaround EVG-12829
-
+#
+# The script is used to setup the environment for a spawn host. Currently the script 
+# unzips the test artefacts, aliases the mongodbtoolchain binaries, installs cmake into the machine,
+# and exports the LD_LIBRARY_PATH.
+# 
+# Once setup, the script will notify the user who spawned the host that it is finished.
+#
+cd $HOME
 TOOLCHAIN_ROOT=/opt/mongodbtoolchain/v4
 
 # Communicate to users that logged in before the script started that nothing is ready.
 wall "The setup_spawn_host script has just started setting up the debugging environment."
 
-# Make a directory on the larger EBS volume. Soft-link it under the home directory. The smaller home
-# volume can have trouble particularly with coredumps from sharded timeouts.
+# Make a directory on the larger volume. Soft-link it under the home directory.
 mkdir -p /data/wiredtiger
 ln -s /data/wiredtiger .
 cd wiredtiger
 
-# Discover and unarchive necessary files and source code. This will put mongo binaries and their
-# partner .debug files in the same `debug/bin` directory. The `bin` directory will later be symbolic
-# linked into the top-level (`debug`) directory. Shared library files and their debug symbols will
-# be dumped into a `debug/lib` directory for tidiness. The mongo `<reporoot>/src/` directory is soft
-# linked as `debug/src`. The .gdbinit file assumes gdb is being run from the `debug` directory.
-WT_ARCHIVE=$(ls /data/mci/artifacts-*/*.tgz 2>/dev/null)
+WT_ARCHIVE=$(ls /data/mci/artifacts-*/*test*.tgz 2>/dev/null)
 if [[ -n $WT_ARCHIVE ]]; then
-    tar --wildcards --strip-components=1 -xzf $BIN_ARCHIVE
-else
-    archive_fail "bin"
+    tar --wildcards -xzf $WT_ARCHIVE
 fi
 
-# Symbolic linking all of the executable files is sufficient for `gdb ./mongod ./dump_mongod.core`
-# to succeed. This inadvertantly also links in the ".debug" files which is unnecessary, but
-# harmless. gdb expects the .debug files to live adjacent to the physical binary.
-find bin -type f -perm -o=x -exec ln -s {} cmake_build \;
+COMPILE_ARCHIVE=$(ls /data/mci/artifacts-*/*compile*.tgz 2>/dev/null)
+if [[ -n $COMPILE_ARCHIVE ]]; then
+   tar --wildcards -xzf $COMPILE_ARCHIVE
+fi
 
-cat >> ~/.profile <<EOF
+if [[ -z $COMPILE_ARCHIVE && -z WT_ARCHIVE ]]; then
+    echo "Error: archive test and compile not found." >&2
+fi
+
+echo "Waiting for background processes to complete."
+wait
+
+# Install CMake into the machine.
+. test/evergreen/find_cmake.sh
+
+cat >> ~/.profile << EOF
 # Coredumps generated by a toolchain built mongodb can be problematic when examined with the system
 # gdb.
 alias gdb='${TOOLCHAIN_ROOT}/bin/gdb'
 alias g++='${TOOLCHAIN_ROOT}/bin/g++'
 alias gcc='${TOOLCHAIN_ROOT}/bin/gcc'
 alias python3='${TOOLCHAIN_ROOT}/bin/python3'
-
-$WT_TOPDIR/TCMALLOC_LIB/lib
-export LD_LIBRARY_PATH="${HOME}/wiredtiger/cmake_build:${HOME}/wiredtiger/TCMALLOC_LIB/LIB:$LD_LIBRARY_PATH"
+alias cmake=${CMAKE}
+export LD_LIBRARY_PATH="${HOME}/wiredtiger/cmake_build:${HOME}/wiredtiger/TCMALLOC_LIB/LIB:\$LD_LIBRARY_PATH"
 EOF
 
     echo 'if [ -f ~/.profile ]; then
     . ~/.profile
-fi' >> .bash_profile
+fi' >> ~/.bash_profile
 
 # Send a Slack notification as the very last thing the setup_spawn_host script does.
-# This way a Server engineer can temporarily forget about the Evergreen host they spawned until the
-# paths and environment variables are configured as intended for when they first connect.
 ssh_user=$(whoami)
 evg_credentials_pathname=~/.evergreen.yml
 evg_binary_pathname=evergreen
